import { ArrowRight, Check, Droplets, Phone, ShieldCheck, Sparkles, Wrench } from 'lucide-react'
import { SiteFooter } from '@/components/site-footer'
import { PageHero, SiteHeader } from '@/components/site-header'

const cleaningImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-2r28IzhlFmocDHnOq8T0EK1IpSXkfV.png'
const toolsImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-sjfOEYSvzozgz0aFj7cuYPcWK44ZED.png'
const chemistryImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-ksA6EhdsBrI00lQHk7Mupsxlq4HtA2.png'
const brushImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-bzfk8MDAGqM8oAaGRlxrOyPKRg7J5X.png'
const testingImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-ZxNFSEVgg6ipnPw5H59FMvH8z8hR7r.png'

export default function Home() {
  return <main className="site-shell"><SiteHeader /><PageHero eyebrow="Aguilar Pool Care" title={<>A cleaner pool.<br /><em>More time to enjoy it.</em></>} description="Professional residential pool care so you can enjoy crystal-clear water without spending your free time cleaning it." image={cleaningImage} />
    <section className="trust-strip"><div className="container trust-grid"><div><strong>15+</strong><span>Years of experience</span></div><div><strong>500+</strong><span>Happy customers</span></div><div><strong>52</strong><span>Visits per year</span></div><div><strong>5.0</strong><span>Average rating</span></div></div></section>
    <section className="section"><div className="container section-heading"><div><span className="kicker">Residential pool care</span><h2>Everything your pool needs<br /><em>to be enjoyed.</em></h2></div><p>We specialize in residential pools, backyards, and communities. We do not service sports facilities; we care for the place where you relax.</p></div><div className="container service-grid">{[[Droplets,'Mantenimiento semanal','Limpieza completa, cepillado, aspirado y balance de químicos.'],[Sparkles,'Limpieza profunda','Rescatamos piscinas verdes, descuidadas o afectadas por tormentas.'],[Wrench,'Equipo y filtros','Revisamos bombas, filtros, skimmers y niveles.'],[ShieldCheck,'Agua segura','Recomendaciones claras para un agua limpia y equilibrada.']].map(([Icon,title,text]) => <article className="service-card" key={String(title)}><div className="service-icon"><Icon /></div><h3>{String(title)}</h3><p>{String(text)}</p><a href="/servicios">Conocer servicio <ArrowRight size={15} /></a></article>)}</div></section>
    <section className="feature-band"><div className="feature-image"><img src={toolsImage} alt="Herramientas y productos para mantenimiento de piscina" /></div><div className="feature-copy"><span className="kicker">La tranquilidad empieza aquí</span><h2>Nosotros cuidamos<br /><em>cada detalle.</em></h2><p>Aguilar Pool Care combina experiencia, puntualidad y comunicación honesta para que tu piscina se mantenga lista para disfrutarla.</p><a className="button button-primary" href="/contacto">Get a quote <ArrowRight size={18} /></a></div></section>
    <section className="visual-process"><div className="container"><div className="section-heading"><div><span className="kicker">How we work</span><h2>El cuidado está<br /><em>en los detalles.</em></h2></div><p>Desde la revisión del agua hasta el último cepillado, dejamos todo en orden para que tú solo disfrutes.</p></div><div className="visual-grid"><figure><img src={chemistryImage} alt="Especialista revisando químicos de piscina" /><figcaption><b>01</b><span>Chemical balance</span></figcaption></figure><figure><img src={brushImage} alt="Limpieza profesional de piscina con cepillo" /><figcaption><b>02</b><span>Surface cleaning</span></figcaption></figure><figure><img src={testingImage} alt="Prueba de agua y limpieza de piscina" /><figcaption><b>03</b><span>Final inspection</span></figcaption></figure></div></div></section>
    <section className="cta-strip"><div className="container"><div><span className="kicker">¿Hablamos?</span><h2>Tu piscina merece<br /><em>un mejor cuidado.</em></h2></div><a className="button button-primary" href="/contacto">Comenzar ahora <ArrowRight size={18} /></a></div></section><SiteFooter /></main>
}
